volumes:
  postgres_volume:

services:
  pg:
    image: postgres:17.2-alpine3.19
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pg
    environment:
      - "DATABASE_URL=${DATABASE_URL}"
      - "SECRET_KEY=${SECRET_KEY}"
    ports:
      - "${PORT}:8080"